# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\temp\scrap_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 258)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 100, 12))
        self.label.setObjectName("label")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(10, 40, 780, 20))
        self.url.setObjectName("url")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 110, 12))
        self.label_2.setObjectName("label_2")
        self.rb_10min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_10min.setGeometry(QtCore.QRect(10, 120, 50, 20))
        self.rb_10min.setObjectName("rb_10min")
        self.rb_5min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_5min.setGeometry(QtCore.QRect(60, 120, 50, 20))
        self.rb_5min.setObjectName("rb_5min")
        self.rb_1min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1min.setGeometry(QtCore.QRect(100, 120, 50, 20))
        self.rb_1min.setObjectName("rb_1min")
        self.rb_30sec = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_30sec.setGeometry(QtCore.QRect(140, 120, 50, 20))
        self.rb_30sec.setObjectName("rb_30sec")
        self.rb_5ec = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_5ec.setGeometry(QtCore.QRect(190, 120, 50, 20))
        self.rb_5ec.setObjectName("rb_5ec")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(500, 110, 120, 50))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(630, 110, 120, 50))
        self.btn_stop.setObjectName("btn_stop")
        self.lbl_print = QtWidgets.QLabel(self.centralwidget)
        self.lbl_print.setGeometry(QtCore.QRect(10, 190, 770, 40))
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_print.setFont(font)
        self.lbl_print.setText("여기에 결과가 출력됩니다.")
        self.lbl_print.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_print.setObjectName("lbl_print")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.rb_10min.clicked.connect(MainWindow.setCycle)
        self.rb_5min.clicked.connect(MainWindow.setCycle)
        self.rb_1min.clicked.connect(MainWindow.setCycle)
        self.rb_30sec.clicked.connect(MainWindow.setCycle)
        self.rb_5ec.clicked.connect(MainWindow.setCycle)
        self.btn_start.clicked.connect(MainWindow.startChk)
        self.btn_stop.clicked.connect(MainWindow.stopChk)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "웹툰 감지 프로그램"))
        self.label.setText(_translate("MainWindow", "주소 입력하세요."))
        self.label_2.setText(_translate("MainWindow", "주기를 선택하세요."))
        self.rb_10min.setText(_translate("MainWindow", "10분"))
        self.rb_5min.setText(_translate("MainWindow", "5분"))
        self.rb_1min.setText(_translate("MainWindow", "1분"))
        self.rb_30sec.setText(_translate("MainWindow", "30초"))
        self.rb_5ec.setText(_translate("MainWindow", "5초"))
        self.btn_start.setText(_translate("MainWindow", "체크 시작"))
        self.btn_stop.setText(_translate("MainWindow", "체크 종료"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
